name: counter
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backports.zstd=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - cyrus-sasl=2.1.28
  - daiquiri=3.0.0
  - exceptiongroup=1.3.1
  - greenlet=3.3.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - iniconfig=2.3.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libntlm=1.8
  - libpq=18.1
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - ncurses=6.5
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pip=25.3
  - pluggy=1.6.0
  - psycopg2=2.9.10
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.13.11
  - python-json-logger=2.0.7
  - python_abi=3.13
  - readline=8.2
  - requests=2.32.5
  - sqlalchemy=1.4.54
  - tk=8.6.13
  - tomli=2.3.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - zstd=1.5.7
prefix: /home/servilla/miniconda3/envs/counter
